import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ProductProvider } from "@/context/ProductContext";

export const metadata = {
  title: "FASHIONHub",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Navbar />
        <ProductProvider>{children}</ProductProvider>
      </body>
    </html>
  );
}
